/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace Voting {
      
    export type ProposalStruct = {description: string, voteCount: BigNumberish}

    export type ProposalStructOutput = [description: string, voteCount: bigint] & {description: string, voteCount: bigint }
  
    }

  export interface VotingInterface extends Interface {
    getFunction(nameOrSignature: "addProposal" | "checkIfVoted" | "getAllProposals" | "getProposal" | "getProposalCount" | "getWinner" | "hasVoted" | "owner" | "proposals" | "vote"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ProposalCreated" | "Voted"): EventFragment;

    encodeFunctionData(functionFragment: 'addProposal', values: [string]): string;
encodeFunctionData(functionFragment: 'checkIfVoted', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getAllProposals', values?: undefined): string;
encodeFunctionData(functionFragment: 'getProposal', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getProposalCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getWinner', values?: undefined): string;
encodeFunctionData(functionFragment: 'hasVoted', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'proposals', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'vote', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'addProposal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'checkIfVoted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllProposals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProposal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProposalCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getWinner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasVoted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vote', data: BytesLike): Result;
  }

  
    export namespace ProposalCreatedEvent {
      export type InputTuple = [proposalId: BigNumberish, description: string];
      export type OutputTuple = [proposalId: bigint, description: string];
      export interface OutputObject {proposalId: bigint, description: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VotedEvent {
      export type InputTuple = [voter: AddressLike, proposalId: BigNumberish];
      export type OutputTuple = [voter: string, proposalId: bigint];
      export interface OutputObject {voter: string, proposalId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Voting extends BaseContract {
    
    connect(runner?: ContractRunner | null): Voting;
    waitForDeployment(): Promise<this>;

    interface: VotingInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addProposal: TypedContractMethod<
      [description: string, ],
      [void],
      'nonpayable'
    >
    

    
    checkIfVoted: TypedContractMethod<
      [voter: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    getAllProposals: TypedContractMethod<
      [],
      [Voting.ProposalStructOutput[]],
      'view'
    >
    

    
    getProposal: TypedContractMethod<
      [proposalId: BigNumberish, ],
      [[string, bigint] & {description: string, voteCount: bigint }],
      'view'
    >
    

    
    getProposalCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getWinner: TypedContractMethod<
      [],
      [[bigint, string, bigint] & {winningProposalId: bigint, winningProposalDescription: string, winningVoteCount: bigint }],
      'view'
    >
    

    
    hasVoted: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    proposals: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint] & {description: string, voteCount: bigint }],
      'view'
    >
    

    
    vote: TypedContractMethod<
      [proposalId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addProposal'): TypedContractMethod<
      [description: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'checkIfVoted'): TypedContractMethod<
      [voter: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'getAllProposals'): TypedContractMethod<
      [],
      [Voting.ProposalStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getProposal'): TypedContractMethod<
      [proposalId: BigNumberish, ],
      [[string, bigint] & {description: string, voteCount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getProposalCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getWinner'): TypedContractMethod<
      [],
      [[bigint, string, bigint] & {winningProposalId: bigint, winningProposalDescription: string, winningVoteCount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'hasVoted'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'proposals'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint] & {description: string, voteCount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'vote'): TypedContractMethod<
      [proposalId: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ProposalCreated'): TypedContractEvent<ProposalCreatedEvent.InputTuple, ProposalCreatedEvent.OutputTuple, ProposalCreatedEvent.OutputObject>;
getEvent(key: 'Voted'): TypedContractEvent<VotedEvent.InputTuple, VotedEvent.OutputTuple, VotedEvent.OutputObject>;

    filters: {
      
      'ProposalCreated(uint256,string)': TypedContractEvent<ProposalCreatedEvent.InputTuple, ProposalCreatedEvent.OutputTuple, ProposalCreatedEvent.OutputObject>;
      ProposalCreated: TypedContractEvent<ProposalCreatedEvent.InputTuple, ProposalCreatedEvent.OutputTuple, ProposalCreatedEvent.OutputObject>;
    

      'Voted(address,uint256)': TypedContractEvent<VotedEvent.InputTuple, VotedEvent.OutputTuple, VotedEvent.OutputObject>;
      Voted: TypedContractEvent<VotedEvent.InputTuple, VotedEvent.OutputTuple, VotedEvent.OutputObject>;
    
    };
  }